Console.WriteLine("Scanning Files...");
Thread.Sleep(4000);
Console.WriteLine("Files Detected!!");
Thread.Sleep(1000);
Console.WriteLine("All Files Founded In Windows/System32!");
Thread.Sleep(1000);
Console.WriteLine("Deleting");
Thread.Sleep(2000);
Console.WriteLine("Files Sucessfully Deleted!");
Thread.Sleep(1000);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
Console.WriteLine("SYSTEM FILES NOT FOUND!");
Thread.Sleep(930);
